FROM mongo:3

ENV sourcesdir /app
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN apt-get update && apt-get install -yq git curl

RUN curl -sSL https://storage.googleapis.com/golang/go1.16.linux-amd64.tar.gz -o go.tar.gz && \
    tar -C /usr/local -xvf go.tar.gz

COPY . ${sourcesdir}
WORKDIR ${sourcesdir}
RUN go env -w GOPROXY=direct && go mod download