FROM golang:1.16-buster AS build

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
#RUN go mod download
RUN go env -w GOPROXY=direct && go mod download
COPY . .

RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o /user main.go
RUN chmod +x /user && chown 65534:65534 /user && \
	setcap CAP_NET_BIND_SERVICE=+eip /user

FROM gcr.io/distroless/base-debian11

ENV HATEAOS user
ENV USER_DATABASE mongodb
ENV MONGO_HOST user-db

WORKDIR /
EXPOSE 8080
COPY --from=build /user /

USER 65534

CMD ["/user", "-port=8080"]